/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sprnil(props) {
  const { nodes, materials } = useGLTF('/sprnil.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spiral.geometry}
        material={materials.Material}
      />
    </group>
  )
}

useGLTF.preload('/sprnil.glb')
